default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: trantor
  password: Dfr368qE
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: trantor_constellation_development

test:
  <<: *default
  database: trantor_constellation_test

production:
  <<: *default
  database: trantor_constellation_production
  username: trantor_constellation
  password: <%= ENV["TRANTOR_CONSTELLATION_DATABASE_PASSWORD"] %>
