default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: trantorconstellation
  password: Dfr368qE
  host: localhost

development:
  <<: *default
  database: trantorconstellationdevelopment

test:
  <<: *default
  database: trantorconstellationtest

production:
  <<: *default
  database: trantorconstellationproduction
